apiVersion: apps/v1
kind: Deployment
metadata:
  name: cu-ms-proyecto1
  namespace: juanjcordero-dev
  labels:
    app: cu-ms-proyecto1
    areanegocio: pagos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cu-ms-proyecto1
  template:
    metadata:
      labels:
        app: cu-ms-proyecto1
    spec:
      containers:
        - name: hola-mundo
          image: juanjcordero/cu-ms-proyecto1:{{ imageTag }}
          ports:
            - containerPort: 3005
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: /startup
              port: 3005
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /liveness
              port: 3005
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 3005
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            initialDelaySeconds: 5
          envFrom:
            - configMapRef:
                name: cu-ms-proyecto1

---
apiVersion: v1
kind: Service
metadata:
  name: cu-ms-proyecto1
  namespace: juanjcordero-dev
spec:
  selector:
    app: cu-ms-proyecto1
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cu-ms-proyecto1
  namespace: juanjcordero-dev
data:
  LOG_LEVEL: "debug"
  MICROSERVICE_URL: "http://cu-ms-payments:3000"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cu-ms-proyecto1
  namespace: juanjcordero-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cu-ms-proyecto1
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90